---
title: "Reading Data from the Web"
author: "Kylie Wheelock Riley"
date: "10/10/2019"
output: html_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(rvest)
library(httr)
knitr::opts_chunk$set(echo = TRUE)

```

# Pulling HTML with Rvest

## Read in the NSDUH data

```{r}
url = "http://samhda.s3-us-gov-west-1.amazonaws.com/s3fs-public/field-uploads/2k15StateFiles/NSDUHsaeShortTermCHG2015.htm"

drug_use_xml = read_html(url) 


table_list = (drug_use_xml %>% html_nodes(css = "table"))

table_marj = table_list[[1]] %>% 
  html_table() %>% 
  ##use slice below because the footer at the bottom of the table being used as a header and we wanted to remove it
  slice(-1) %>% 
  as_tibble()
 

```

## Learning Asessment 1
```{r}
url = "https://www.bestplaces.net/cost_of_living/city/new_york/new_york"

COL_NYC = read_html(url)


COL_NYC_table = (COL_NYC %>% html_nodes(css = "table"))

table_comparison = COL_NYC_table[[1]] %>% 
  html_table(header = TRUE)


```

#CSS Selectors

## HP Data
```{r}
hpsaga_html = 
  read_html("https://www.imdb.com/list/ls000630791/")
```

```{r}
hp_movie_names = 
  hpsaga_html %>% 
  ##pull css tag for items of interest through slector gadget
  html_nodes(".lister-item-header a") %>% 
  ## have a nice table, but we want to extraxt the text, so will use html_tex
  html_text()

hp_movie_runtime = 
  hpsaga_html %>% 
  html_nodes(".runtime") %>% 
  html_text()

hp_movie_money = 
  hpsaga_html %>% 
  html_nodes(".text-small:nth-child(7) span:nth-child(5)") %>% 
  html_text()

hp_df = 
  tibble(
    title = hp_movie_names, 
    tuntime = hp_movie_runtime,
    sales = hp_movie_money
  )
  
```


##Learning Assessment 2
```{r}
url = "https://www.amazon.com/product-reviews/B00005JNBQ/ref=cm_cr_arp_d_viewopt_rvwer?ie=UTF8&reviewerType=avp_only_reviews&sortBy=recent&pageNumber=1"

dynamite_html = read_html(url)

review_titles = 
  dynamite_html %>%
  html_nodes(".a-text-bold span") %>%
  html_text()

review_stars = 
  dynamite_html %>%
  html_nodes("#cm_cr-review_list .review-rating") %>%
  html_text()

review_text = 
  dynamite_html %>%
  html_nodes(".review-text-content span") %>%
  html_text()

reviews = tibble(
  title = review_titles,
  stars = review_stars,
  text = review_text
)

```

# Using an API
```{r}
nyc_water_df =
    GET("https://data.cityofnewyork.us/resource/waf7-5gvc.csv") %>% 
  content()

nyc_water = 
  GET("https://data.cityofnewyork.us/resource/waf7-5gvc.json") %>% 
  content("text") %>%
  jsonlite::fromJSON() %>%
  as_tibble()
```


## BRFSS example
```{r}
brfss_data = 
  GET("https://data.cdc.gov/api/views/acme-vg9e/rows.csv?accessType=DOWNLOAD") %>% 
  content("parsed")
```

# Pokemon example
```{r}
poke = 
  GET("http://pokeapi.co/api/v2/pokemon/1") %>%
  content()

poke

poke$name
poke$abilities

```

